name: Build, Push and Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: [self-hosted, linux]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Azure CLI Login with Managed Identity
      run: az login --identity

    - name: Disable Docker credential store (avoid wincred errors)
      run: |
        mkdir -p ~/.docker
        echo '{ "credsStore": "" }' > ~/.docker/config.json

    - name: ACR login
      run: az acr login --name acraksprive

    - name: Build Docker image
      run: docker build -t acraksprive.azurecr.io/sonasid-app:${{ github.run_number }} .

    - name: Push image to ACR
      run: docker push acraksprive.azurecr.io/sonasid-app:${{ github.run_number }}

    - name: Get AKS credentials (admin access)
      run: az aks get-credentials --name aksprive_test --resource-group RG_test_aksprive --admin

    - name: Deploy app (Deployment + Service + Ingress)
      run: |
        sed -i "s/BUILD_ID/dev-${{ github.run_number }}/g" deployment.yml
        kubectl apply -f deployment.yaml
        kubectl apply -f ingress.yaml
