name: Build, Push and Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Azure using Managed Identity
      run: az login --identity

    - name: ACR login with Managed Identity
      run: az acr login --name acraksprive

    - name: Build Docker image
      run: docker build -t acraksprive.azurecr.io/sonasid-app:v1 .

    - name: Push image to ACR
      run: docker push acraksprive.azurecr.io/sonasid-app:v1

    - name: Get AKS credentials
      run: az aks get-credentials --name aksprive_test --resource-group RG_test_aksprive --admin

    - name: Deploy to AKS
      run: kubectl apply -f deployment.yaml
