name: Build, Push and Deploy to AKS (Private Cluster)

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to Azure using Managed Identity
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Azure ACR Login
      run: az acr login --name acraksprive

    - name: Build Docker Image
      run: docker build -t acraksprive.azurecr.io/sonasid-app:v1 .

    - name: Push Docker Image
      run: docker push acraksprive.azurecr.io/sonasid-app:v1

    - name: Get AKS credentials
      run: az aks get-credentials --name aksprive_test --resource-group RG_test_aksprive --admin

    - name: Deploy to AKS
      run: kubectl apply -f deployment.yaml

    - name: Verify Deployment
      run: kubectl get pods
