name: Build, Push and Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Docker Login to ACR
      run: echo "${{ secrets.ACR_PASSWORD }}" | docker login acraksprive.azurecr.io -u ${{ secrets.ACR_USERNAME }} --password-stdin

    - name: Build Docker Image
      run: docker build -t acraksprive.azurecr.io/sonasid-app:v1 .

    - name: Push Docker Image
      run: docker push acraksprive.azurecr.io/sonasid-app:v1

    - name: Get AKS credentials
      run: az aks get-credentials --resource-group RG_test_aksprive --name aksprive_test

    - name: Set image in AKS deployment
      run: |
        kubectl set image deployment/sonasid-app sonasid=acraksprive.azurecr.io/sonasid-app:v1 --namespace default
